### PR TITLE
The testing should include multistream

### PR DESCRIPTION
**Pull request by efajardo**
The testing should include multiple streams

### CODE REVIEW

**Comment by brianhlin** [comment]
@efajardo do you have a corresponding VMU run?

**Comment by efajardo** [comment]
@brianhlin nop but we found out that 5.1.0 broke multistream tpc that was working on 5.0.2 so I wanted to add this so this is caught.

**Comment by efajardo** [comment]
Things look good in this [VMU Tests](https://osg-sw-submit.chtc.wisc.edu/tests/20210105-1303/results.html) @brianhlin

**Comment by brianhlin** [comment]
Hey @efajardo I spot-checked a few of the outputs and didn't see any `X-Number-Of-Streams` headers so I think something's up

**Comment by efajardo** [comment]
The new [VMU tests](https://osg-sw-submit.chtc.wisc.edu/tests/20210105-1655) show the errors we found out on `5.1.0.rc4`

```
osgtest: 2021-01-05 17:10:06: test_465_xrootd_tpc.py:test_02_initate_tpc:57: runuser vdttest -c "curl -A Test -vk -X COPY -H 'Authorization: Bearer MDAyOGxvY2F0aW9uIE9TR19URVNUX1hST09URF9TVEFOREFMT05FCjAwMzRpZGVudGlmaWVyIDk0NWYxNTk1LWIxYTMtNGRlYy1iYWZlLWNiYmNkNzVkODAzOAowMDE1Y2lkIG5hbWU6dmR0dGVzdAowMDJkY2lkIGFjdGl2aXR5OlJFQURfTUVUQURBVEEsRE9XTkxPQUQsTElTVAowMDE1Y2lkIGFjdGl2aXR5OkFMTAowMDM3Y2lkIHBhdGg6L3Vzci9zaGFyZS9vc2ctdGVzdC90ZXN0X2dyaWRmdHBfZGF0YS50eHQKMDAyNGNpZCBiZWZvcmU6MjAyMS0wMS0wNVQyMzozMDowNVoKMDAyZnNpZ25hdHVyZSC71RSEGDO1fsZnDeFEP55uyHVdTNEk7QwshTI9L-rQvgo' -H 'Source: https://osg-test.localdomain:9001/usr/share/osg-test/test_gridftp_data.txt' -H 'Overwrite: T' -H 'X-Number-Of-Streams: 2' -H 'Copy-Header:  Authorization: Bearer MDAyOGxvY2F0aW9uIE9TR19URVNUX1hST09URF9TVEFOREFMT05FCjAwMzRpZGVudGlmaWVyIDg3ODhiZjAyLTdkNDgtNGYyOC1iNDE2LTlhMTJmNDE3YjQ3ZAowMDE1Y2lkIG5hbWU6dmR0dGVzdAowMDUyY2lkIGFjdGl2aXR5OlJFQURfTUVUQURBVEEsVVBMT0FELERPV05MT0FELERFTEVURSxNQU5BR0UsVVBEQVRFX01FVEFEQVRBLExJU1QKMDAxNWNpZCBhY3Rpdml0eTpBTEwKMDAyY2NpZCBwYXRoOi90bXAvdGVzdF9ncmlkZnRwX2RhdGFfdHBjLnR4dAowMDI0Y2lkIGJlZm9yZToyMDIxLTAxLTA1VDIzOjMwOjA1WgowMDJmc2lnbmF0dXJlIHK8xGS4SxKqivv5QERTWSSTCeN9a7xNf4RwxF-TE1g0Cg' https://osg-test.localdomain:9002/tmp/test_gridftp_data_tpc.txt" >>> 0 2404 0
STDOUT:{
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to osg-test.localdomain port 9002 (#0)
*   Trying 192.168.122.169...
* Connected to osg-test.localdomain (192.168.122.169) port 9002 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
```

**Comment by brianhlin** [comment]
It doesn't look like 5.1.0 got installed, just 4.12.6. Does this bug also affect the 4.12 series?

**Comment by efajardo** [comment]
We found it on the 5.1.0 series:

https://github.com/xrootd/xrootd/issues/1378

But yea I guess it is also in 4.12 but in 5.0.2 the problem is gone

**Review by brianhlin — APPROVED** [review]
LGTM then

**Pull request merged**
