### PR TITLE
only run bestman tests if gums-service is installed (SOFTWARE-3201)

### PR DESCRIPTION
**Pull request by edquist**

### CODE REVIEW

**Comment by brianhlin** [comment]
Can you kick off VMU tests using your fork + branch?

**Comment by brianhlin** [comment]
@edquist where's this stand?

**Comment by edquist** [comment]
Hey @brianhlin,

I followed up with your request to kick off the VMU tests against my branch in the corresponding JIRA ticket [here](https://jira.opensciencegrid.org/browse/SOFTWARE-3201?focusedCommentId=349880&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-349880).

The VMU run was: http://vdt.cs.wisc.edu/tests/20180411-1501/packages.html

There are notes in the jira ticket starting with [this comment](https://jira.opensciencegrid.org/browse/SOFTWARE-3201?focusedCommentId=349889&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-349889).

Otherwise this PR was waiting on your review for merging.

Let me know if you'd like to see another run against this branch or anything.

**Comment by brianhlin** [comment]
Thanks for the detailed refresher!

**Pull request merged**
