### PR TITLE
Use Python 3

### PR DESCRIPTION
**Pull request by matyasselmeci**
This was mostly just converting osg-test-log-viewer to Python 3

### CODE REVIEW

**Comment by brianhlin** [comment]
Do you have a test run using this branch?

**Comment by matyasselmeci** [comment]
Just kicked one off; note that we need to merge https://github.com/opensciencegrid/vm-test-runs/pull/167 before we can merge this.

**Comment by matyasselmeci** [comment]
https://osg-sw-submit.chtc.wisc.edu/tests/20210824-0846/packages.html

**Review by brianhlin — APPROVED** [review]
(Mostly) Green means go

**Pull request merged**
