### PR TITLE
Add TLS configuration lines

### PR DESCRIPTION
**Pull request by djw8605**

### CODE REVIEW

**Review by efajardo — COMMENTED** [review]
@djw8605,
Should we add the TLS for the test_158 TPC tests?

**Comment by djw8605** [comment]
The TPC you are referring to does HTTP TPC right?  So this TLS configuration doesn't matter at all, right?

**Comment by efajardo** [comment]
@djw8605 that is correct but it is the configuration we will be shipping the osg-standalone which the TPC uses so it should be added  to the tests. Even if they are not strictly needed

**Comment by djw8605** [comment]
Sure, sounds good.

**Review by brianhlin — COMMENTED** [review]
@djw8605 do we still need this? @matyasselmeci may be worth looking at since you're fiddling with the XRootD config

**Comment by matyasselmeci** [comment]
Sure, let me kick off a VMU run.

**Comment by matyasselmeci** [comment]
https://osg-sw-submit.chtc.wisc.edu/tests/20210830-1745/results.html
Derek, is your master branch up to date? Those are some real bizarre errors in the test output.

**Comment by djw8605** [comment]
The pull request is from August 2020, so probably not up to date.  I just merged in master of the osg repo.

**Comment by matyasselmeci** [comment]
https://osg-sw-submit.chtc.wisc.edu/tests/20210831-1052/packages.html looks good to me. @brianhlin , any objections, or can I merge?

**Comment by brianhlin** [comment]
Go for it

**Pull request merged**
